export default {
  container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  formLabel: {
    fontSize: 20,
    color: '#fff',
  },
  inputStyle: {
    marginTop: 20,
    width: 300,
    height: 40,
    paddingHorizontal: 10,
    paddingLeft: 24,
    borderRadius: 50,
    borderColor: '#08935e',
    borderWidth: 1,
    overflow: 'hidden',
  },
  inputStyle2: {
    marginTop: 20,
    width: 300,
    height: 40,
    paddingHorizontal: 10,
    borderRadius: 50,
    borderColor: '#08935e',
    borderWidth: 1,
    overflow: 'hidden',
  },
  pickerStyle: {
    marginTop: 20,
    width: 300,
    height: 40,
    paddingHorizontal: 10,
    borderRadius: 10,
    overflow: 'hidden',
  },
  formText: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ed6c1c',
    fontSize: 20,
  },
  text: {
    color: '#010101',
    fontSize: 20,
  },
  button: {
    justifyContent: 'center',
    backgroundColor: '#ed6c1c',
    flexDirection: 'row',
    padding: 10,
    width: 300,
    marginTop: 24,
    borderRadius: 24,
  },
  item: {},
  label: {
    marginLeft: 16,
    marginTop: 8,
    fontSize: 12,
    color: '#ed6c1c',
  },
  sendButton: {
    marginVertical: 16,
    backgroundColor: '#ed6c1c',
  },
  title: {
    alignSelf: 'center',
    color: '#ed6c1c',
    fontWeight: 'bold',
  },
};
