export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';

export const SET_USERDATA_IN_SESSION = 'SET_USERDATA_IN_SESSION';
export const GET_USERDATA_FROM_SESSION = 'GET_USERDATA_FROM_SESSION';
export const REMOVE_USERDATA_FROM_SESSION = 'REMOVE_USERDATA_FROM_SESSION';
export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
